/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xu_jnisademo_myJNI */
//打开android studio终端，使用javac编译上述文件，生成class文件。然后就能看到生成了一个h文件。
//所以我的javah命令应该这么写: D:\AndroidStudioProject\testJNI\app\src\main\java>javah -jni com.example.binbin.testjni.myJNI

#ifndef _Included_com_xu_jnisademo_myJNI
#define _Included_com_xu_jnisademo_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xu_jnisademo_myJNI
 * Method:    saHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xu_jnisademo_myJNI_saHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
